AWSTemplateFormatVersion: "2010-09-09"
Resources:
   myStackWithParam:
       Type: AWS::CloudFormation::Stack
       Properties:
          TemplateURL:""
          Parameters:
             InstanceType: t1.micro
             De
